name = "see-it-say-it"
compatibility_date = "2026-03-29"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist/client"
binding = "ASSETS"

[vars]
APP_BASE_URL = "https://see-it-say-it.steven-896.workers.dev"
RESEND_FROM_EMAIL = "onboarding@resend.dev"

[[d1_databases]]
binding = "DB"
database_name = "see-it-say-it-db"
database_id = "ffe7de88-28cf-420a-81c3-f7793ff41ff4"
